# Generated by Django 6.0.2 on 2026-02-12 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('report_type', models.CharField(choices=[('yardim', '🚑 ACİL YARDIM'), ('kayip', '🔎 KAYIP / BULUNDU')], default='yardim', max_length=10)),
                ('status', models.CharField(choices=[('acil', '🔴 ACİL DURUM'), ('bekliyor', '🟡 Bekliyor'), ('cozuldu', '🟢 Çözüldü')], default='acil', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
